services:
- type: pserv
  name: elasticsearch
  env: docker
  plan: standard
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 0.1
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms100m -Xmx200m"
  - key:- xpack.security.enabled
    value: false
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
